name: JS Dev Starter CI

env:
    DOCKER_BUILDKIT: 1

on:
    push:
        branches: [ main, develop ]
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.[0-9]+'
    pull_request:
        branches: [ main, develop ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build_app:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 18.x ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Branch
                id: short_ref
                run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
            -   name: Set git_url_commit
                id: git_url_commit
                run: echo ::set-output name=git_url_commit::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
            -   name: Set git_url_ci_run
                id: git_url_ci_run
                run: echo ::set-output name=git_url_ci_run::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
            -   name: Set git_commit
                id: git_commit
                run: echo ::set-output name=git_commit::${GITHUB_REPOSITORY}/${GITHUB_SHA}
            -   name: Set git_ci_run
                id: git_ci_run
                run: echo ::set-output name=git_ci_run::${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: Cache CI node_modules
                uses: actions/cache@v3
                env:
                    cache-name: cache-node-modules
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}

            -   name: Install Deps STARTER
                run: |
                    npm ci
                    touch .env
                    echo "SERVICE_NAME=your-project" >> .env

            -   name: Build STARTER [DEV]
                if: github.ref == 'refs/heads/develop'
                env:
                    APP_ENV: dev
                    REACT_APP_VERSION: ${{ steps.git_commit.outputs.git_commit }}
                    REACT_APP_BASE_PATH: ""
                run: |
                    npm run build
                    node makeBuildInfo.js
                    echo "NODE_ENV=production" >> .env
                    echo "APP_ENV=${APP_ENV}" >> .env

            -   name: Build STARTER [PROD]
                if: github.ref == 'refs/heads/main'
                env:
                    APP_ENV: prod
                    REACT_APP_VERSION: ${{ steps.git_commit.outputs.git_commit }}
                    REACT_APP_BASE_PATH: ""
                run: |
                    npm run build
                    node makeBuildInfo.js
                    echo "NODE_ENV=production" >> .env
                    echo "APP_ENV=${APP_ENV}" >> .env

            -   name: Build STARTER [TAG]
                if: startsWith(github.ref, 'refs/tags/')
                env:
                    APP_ENV: prod
                    REACT_APP_VERSION: ${{ steps.short_ref.outputs.short_ref }}
                    REACT_APP_BASE_PATH: ""
                run: |
                    npm run build
                    node makeBuildInfo.js
                    echo "NODE_ENV=production" >> .env
                    echo "APP_ENV=${APP_ENV}" >> .env
